### ISSUE TITLE
Problem when trying to install plugin

### ISSUE THREAD

**Issue by currim** [spasma/cordova-plugin-tts-advanced#1]
When I try to install the plugin using the command: `cordova plugin add cordova-plugin-tts-2`

It gives an error: 

```
npm ERR! 404  'cordova-plugin-tts-2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```
However, the following command works: `npm i cordova-plugin-tts-advanced`

**Comment by spasma** [comment]
@currim Thank you currim, I just updated the Readme 👍
