### ISSUE TITLE
then not called on Android

### ISSUE THREAD

**Issue by andersborgabiro** [spasma/cordova-plugin-tts-advanced#2]
As it says, then() is not called after successful speak() on Android 7.0 (what I tested with). It works on iOS.

**Comment by spasma** [comment]
Thanks @saqimtiaz for the patch. Just tested and published it to npm. 👏

**Comment by saqimtiaz** [comment]
@spasma you're welcome! I had planned to submit a PR once I had the opportunity to test it a bit more.

**Comment by andersborgabiro** [comment]
Thanks 👍
