### ISSUE TITLE
getVoices() unexpected behavior

### ISSUE THREAD

**Issue by blukis** [spasma/cordova-plugin-tts-advanced#4]
If I call `TTS.getVoices().then( function(x) { alert(JSON.stringify(x)); } );`, I get some unexpected stuff:

- Android: nothing happens, .then() is never called.
- iOS: app force-closes.

Aside: what is the purpose of this function?  I was hoping to get something back I could use to call speak() with an explicit voice specified.  It's not documented in the README, so maybe I just shouldn't be calling it! ;)

**Comment by spasma** [comment]
Hi @blukis, 

I have updated the getVoices function on both iOS and Android. A new version was just released on npm!
The function is to gather the available voices from the OS. It returns an identifier to speak a language of choice.

Let me know if it's working for you.

Seb

**Comment by blukis** [comment]
Confirmed - getVoices() now returns a big JS object on both iOS & Android.  (I haven't tested using the identifier in speak(), but the issue is solved.)  Thanks!
