### ISSUE TITLE
How do I use this with typescript and ionic?

### ISSUE THREAD

**Issue by Simbaclaws** [spasma/cordova-plugin-tts-advanced#5]
Dear spasma,

I would like to use your plugin since it supports voice.
However, I'm unable to figure out which typescript plugin to import because I can't seem to find any type declarations other than in the readme.

Are we supposed to add this typescript ourselves somewhere?

I would like to use this inside of ionic, ionic-native has wrapper typescript for the cordova-plugin-tts.
But this is not available for cordova-plugin-tts-advanced...

I'll go ahead and try to create a index.d.ts file and make a pull request, see if that works...
If you would also like to help me out on this issue I would very much appreciate it.

**Comment by spasma** [comment]
Hi @Simbaclaws,

I'm currently using my plugin in a ionic project myself using
`declare var TTS: any;` 
on the top of the .ts-file where you'll use the plugin (as TTS is the global Cordova item), but you won't get autocompletion with that.

An index.d.ts would be nice! Go ahead, I didn't have the time to do it myself.

**Comment by Simbaclaws** [comment]
Hey @spasma,

I have a index.d.ts file but it's not working right now for importing the typescript part of the application.
I even went as far as copying the ionic-native plugin that implements the other plugin and adjusting it to work with this plugin instead. But I couldn't get this to work so far.

I'll try your solution instead.
Thanks for the help :)

**Comment by Simbaclaws** [comment]
Apparently when I set rate to 1 it speaks insanely fast on iOS. Is this normal? Or do I need to set the speech rate to 0.75?

**Comment by spasma** [comment]
@Simbaclaws, if you want to set the rate on iOS, you have to multiply the rate with 0.5, apparently iOS has implemented this the wrong way. I'll fix this is a later version of the plugin. So 1 = 0.5 and 2 (super fast) is 1.

In older versions of iOS the rate was as it should, but somehow this is the way now.

**Comment by Simbaclaws** [comment]
Actually, the rate when set to 0 returns the normal speaking rate, I found out this works for both android and iOS. So I'm thinking that it starts at 0 and is multiplied after 0 towards one.

**Comment by spasma** [comment]
@Simbaclaws No, the range is from 0-1, iOS needs a *0.5 for the rate. 0 is not a valid value, so it picks the default value internally

**Comment by Simbaclaws** [comment]
Thank you, I just noticed it in my console that it's reverting back to default values. I guess this issue can be closed :)
