### ISSUE TITLE
Name is the same as identifier when fetching voices (Android)

### ISSUE THREAD

**Issue by Simbaclaws** [spasma/cordova-plugin-tts-advanced#7]
Hey,

I'm trying to implement an ion-select where the user is able to select which voice they want to use inside of the app.
However, both the name and identifier of a voice is the same in android. Normally you would see voice 1 or voice 2 on android as name of the voice when you look in the settings for switching voices. But this is returning the same data as the identifier.

This way users will have a hard time figuring out which voice is which, because these strings look quite tedious instead of having an actual name for the voice.

There is also no "default" property for the voices. This way I'm unable to set the ion-select to the default value of the device.

I haven't tested this on iOS yet.

EDIT: I just tested this on iOS, and there it does seem to show a correct name, but still not a default property.

**Comment by blukis** [comment]
I am experiencing this also.  Would be great to get "name" to match what is seen in Android settings UI, if it's possible.

**Comment by givethanks1** [comment]
Yes, agree -- this is an Android limitation and not a plugin limitation.

**Comment by Simbaclaws** [comment]
Agreed, issue is android SDK related. I'll close this issue.
